config/routes.rb
Rails.application.routes.draw do

  get 'orders/user'

  get 'orders/invoice', to: 'orders#invoice'

  get 'carts/index', to: 'carts#index'

  get 'pages/about'

  get 'pages/contact'

  post '/products', to: 'products#filter_data'

  post '/carts/index', to: 'carts#refresh_cart'

  post '/products/:id', to: 'products#add_to_cart'

  post '/orders/user', to: 'orders#add_user'

  post 'orders/done', to: 'orders#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources 'products', only: [:index, :show]

  resources 'provinces', only: [:index, :show]

  root to: 'products#index'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  has_many :products
  belongs_to :user
  validates :status, inclusion: { in: %w[paid shipped ordered] }
  # validates :pst_rate, :gst_rate, :hst_rate, numericality: { only_integer: true }

  # gets order number to display instead of object reference id
  def display_name
    id
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def user
    @provinces = Province.all
  end

  def invoice
    @user = User.find(session[:user])
    session_details
  end

  def done
    @user = User.find(session[:user])
    add_order(@user)
    reset_session
  end

  def add_user
    user = User.create(name: params[:customer_name],
                       address: params[:customer_address],
                       city: params[:city],
                       postal_code: params[:postal_code],
                       email: params[:customer_email],
                       phone_number: params[:phone1],
                       is_admin: false,
                       province_id: params[:province])
    if !user.valid?
      flash[:user] = user.errors.messages
      @provinces = Province.all
      render :user
    else
      session[:user] = user.id
      redirect_to('/orders/invoice')
    end
  end

  def add_order(user)
    province = Province.find(user.province_id)
    order = Order.create(status: 'paid',
                         pst_rate: province.pst,
                         gst_rate: province.gst,
                         hst_rate: province.hst,
                         user_id: user.id)
    add_line_items(order)
  end

  def add_line_items(order)
    session[:cart].each do |item|
      product = Product.find(item[0])
      line_item = LineItem.create(quantity: item[1].to_i,
                                  price: product.price,
                                  order_id: order.id,
                                  product_id: product.id)
    end
  end

  def session_details
    @cart_items = session[:cart]
    array_of_ids = []
    @total = 0
    @cart_items.each do |item|
      array_of_ids << item[0]
      @total += (Product.find(item[0]).price * item[1])
    end
    @products = Product.where(id: array_of_ids)
    render :invoice
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_item.html.slim
- quantity = 0 
- @cart_items.find do |l| 
    - if l[0] == item.id 
      - quantity = l[1]
tr
  td.col-md-3
    .media
      a.thumbnail.pull-left href="#" 
        = image_tag item.image.url(:small)
      .media-body
        h4.media-heading = item.name
        h5.media-heading = item.description
  td.text-center = number_to_currency(item.price)
  td.text-center = quantity

app/views/orders/done.html.slim
h1
  | ORDER COMPLETED

app/views/orders/invoice.html.slim
#page-content-wrapper
  button.hamburger.is-closed data-toggle="offcanvas" type="button" 
    span.hamb-top
    span.hamb-middle
    span.hamb-bottom
  .container
    .row
      .col-lg-8.col-lg-offset-2
        .container
        = form_tag orders_done_path do |f|
          .row
            .col-md-12
              .invoice-title
                h2 Please confirm your order
                hr/
              .row
                .col-xs-6
                  address
                    strong Customer Address:
                    br/
                    = @user.name
                    br/
                    = @user.address
                    br/
                    = @user.city
                    | , 
                    = @user.province.name
                    |  
                    =@user.postal_code
          .row
            .col-md-12
              .panel.panel-default
                .panel-heading
                  h3.panel-title
                    strong Item Summary
                .panel-body
                  .table-responsive
                    table.table.table-condensed
                      thead
                        tr
                          td
                            strong Product
                          td.text-center
                            strong Price
                          td.text-center
                            strong Quantity
                      tbody
                        /! foreach ($order->lineItems as $line) or some such thing here
                        =render partial: 'item', collection: @products
          .row
            .col-md-12
              .col-md-4
                h3.text-center Order Summary
                hr/
                .pull-left
                  h4 Subtotal
                .pull-right
                  h4.text-right = number_to_currency(@total)
                - if @user.province.gst
                  .clearfix
                  .pull-left
                    h4 GST: 
                  .pull-right
                    h4.text-right = number_to_currency((@user.province.gst/100)*@total)
                    - @total += (@user.province.gst/100)*@total
                - if @user.province.pst
                  .clearfix
                  .pull-left
                    h4 PST: 
                  .pull-right
                    h4.text-right = number_to_currency((@user.province.pst/100)*@total)
                    - @total += (@user.province.pst/100)*@total
                - if @user.province.hst
                  .clearfix
                  .pull-left
                    h4 HST: 
                  .pull-right
                    h4.text-right = number_to_currency((@user.province.hst/100)*@total)  
                    - @total += (@user.province.hst/100)*@total  
                .clearfix
                .pull-left
                  h4 Order Total
                .pull-right
                  h4.text-right = number_to_currency(@total)
                .clearfix
                .form-group
                  .col-md-4
                    button.btn.btn-primary id="submit" name="submit" type="submit"  Confirm Your Order
          
=debug params
=debug session[:cart]


  
  

app/views/orders/user.html.slim
#page-content-wrapper
  button.hamburger.is-closed data-toggle="offcanvas" type="button" 
    span.hamb-top
    span.hamb-middle
    span.hamb-bottom
  .container
    .row
      .col-lg-8.col-lg-offset-2
        .page-header
          h1
            | Shipping Details
          =form_tag orders_user_path do |f|
            form.form-horizontal              
                /! Form Name
                legend CUSTOMER
                /! Text input
                .form-group
                  label.col-md-4.control-label for="customer_name"  CUSTOMER NAME
                  .col-md-4
                    input#customer_name.form-control.input-md name="customer_name" placeholder=("CUSTOMER NAME") required="" type="text" /
                /! Text input
                .form-group
                  label.col-md-4.control-label for="customer_email"  CUSTOMER EMAIL
                  .col-md-4
                    input#customer_email.form-control.input-md name="customer_email" placeholder=("CUSTOMER EMAIL") required="" type="text" /
                /! Text input
                .form-group
                  label.col-md-4.control-label for="customer_address"  ADDRESS
                  .col-md-4
                    input#customer_address.form-control.input-md name="customer_address" placeholder=("ADDRESS") type="text" /
                /! Text input
                .form-group
                  label.col-md-4.control-label for="city"  CITY
                  .col-md-4
                    input#city.form-control.input-md name="city" placeholder="CITY" required="" type="text" /
                .form-group  
                  label.col-md-4.control-label for="province"  PROVINCE
                  .col-md-4  
                    =collection_select(nil, :province_id, @provinces, :id, :name, {selected: @province, prompt: "PROVINCE"}, {class: 'form-control input-md', name: 'province' })   
                /! Text input
                .form-group
                  label.col-md-4.control-label for="postal_code"  POSTAL CODE
                  .col-md-4
                    input#postal_code.form-control.input-md name="postal_code" placeholder="POSTAL CODE" required="" type="text" /
                /! Text input
                .form-group
                  label.col-md-4.control-label for="phone1"  PHONE NUMBER
                  .col-md-4
                    input#phone1.form-control.input-md name="phone1" placeholder="PHONE1" required="" type="text" /
                /! Button
                .form-group
                  label.col-md-4.control-label for="submit" 
                  .col-md-4
                    button.btn.btn-primary id="submit" name="submit" type="submit"  Submit
=debug params