config/routes.rb
Rails.application.routes.draw do

  get 'orders/user'

  get 'orders/invoice', to: 'orders#invoice'

  get 'carts/index', to: 'carts#index'

  get 'pages/about'

  get 'pages/contact'

  post '/products', to: 'products#filter_data'

  post '/carts/index', to: 'carts#refresh_cart'

  post '/products/:id', to: 'products#add_to_cart'

  post '/orders/user', to: 'orders#add_user'

  post 'orders/done', to: 'orders#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources 'products', only: [:index, :show]

  resources 'provinces', only: [:index, :show]

  root to: 'products#index'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    session_details
  end

  def refresh_cart
    id = params[:id].to_i
    quantity = params[:quantity].to_i
    update_quantity(id, quantity) if params.key?(:refresh)
    delete_item(id) if params.key?(:delete)
  end

  def update_quantity(id, quantity)
    session[:cart].each do |item|
      item[1] = quantity if id == item[0]
    end
    session_details
  end

  def delete_item(id)
    session[:cart].each do |item|
      session[:cart].delete(item) if id == item[0]
    end
    session_details
  end

  def session_details
    @cart_items = session[:cart]
    array_of_ids = []
    @total = 0
    if @cart_items
      @cart_items.each do |item|
        array_of_ids << item[0]
        @total += (Product.find(item[0]).price * item[1])
      end
    end
    @products = Product.where(id: array_of_ids)
    render :index
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_item.html.slim
- quantity = 0 
- @cart_items.find do |l| 
    - if l[0] == item.id 
      - quantity = l[1]
= form_tag carts_index_path do |f|
  tr
    td data-th="Product" 
      .row
        .col-sm-5.hidden-xs
          = image_tag item.image.url(:small)
        .col-sm-7
          h4.nomargin = item.name
          p = item.description
    td data-th="Price"  = number_to_currency(item.price)
    td data-th="Quantity" 
      input.hidden name="id" value=(item.id) /
      input.form-control.text-center name="quantity" min="0" type="number" value=(quantity) /
    td.text-center data-th="Subtotal"  = number_to_currency(item.price*quantity)
    td.actions data-th="" 
      button#refresh.btn.btn-info.btn-sm name="refresh" type="submit"
        i.fa.fa-refresh                       
      button#trash.btn.btn-danger.btn-sm name="delete" type="submit"
        i.fa.fa-trash-o

app/views/carts/index.html.slim
/ bootsnipp for product table cred: http://bootsnipp.com/snippets/featured/responsive-shopping-cart
link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" /
#page-content-wrapper
  button.hamburger.is-closed data-toggle="offcanvas" type="button" 
    span.hamb-top
    span.hamb-middle
    span.hamb-bottom
  .container
    .row
      .col-lg-8.col-lg-offset-2
        .page-header
          h1
            | Shopping Cart
          .container
            table#cart.table.table-hover.table-condensed
              thead
                tr
                  th style="width:50%"  Product
                  th style="width:10%"  Price
                  th style="width:8%"  Quantity
                  th.text-center style="width:22%"  Subtotal
                  th style="width:10%" 
                tbody
                  =render partial: 'item', collection: @products
              tfoot
                tr
                  td
                    a.btn.btn-warning.pull-left href="/products" type="submit"
                      i.fa.fa-angle-left
                      | Continue Shopping
                  td.hidden-xs colspan="2" 
                  td.hidden-xs.text-center
                    strong 
                      | Total 
                      = number_to_currency(@total)
                  - if @total > 0
                    td
                      a.btn.btn-success.btn-block href="/orders/user"  type="submit"
                        | Checkout
                        i.fa.fa-angle-right

=debug params
=debug session[:cart]
              


  
  