config/routes.rb
Rails.application.routes.draw do

  get 'orders/user'

  get 'orders/invoice', to: 'orders#invoice'

  get 'carts/index', to: 'carts#index'

  get 'pages/about'

  get 'pages/contact'

  post '/products', to: 'products#filter_data'

  post '/carts/index', to: 'carts#refresh_cart'

  post '/products/:id', to: 'products#add_to_cart'

  post '/orders/user', to: 'orders#add_user'

  post 'orders/done', to: 'orders#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources 'products', only: [:index, :show]

  resources 'provinces', only: [:index, :show]

  root to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :artist
  belongs_to :product_type
  has_many :orders
  has_attached_file :image, styles: { small: '160x160>' }
  validates_attachment_content_type :image,
                                    content_type:
                                    ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
  paginates_per 5
  validates :name, :description, :price, :stock_quantity, presence: true
  validates :price, :stock_quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :new, :on_sale, inclusion: { in: [true, false] }
  validates :new, :on_sale, exclusion: { in: [nil] }

  def self.search_by_category(artist, search_term)
    products = Product.joins(:artist, :product_type)
                      .where('products.name ILIKE ?'\
                             ' OR products.name ILIKE ?' \
                             ' OR products.name ILIKE ?', \
                             "% #{search_term}", "#{search_term} %",
                             "% #{search_term} %")
    products = products.where('artists.id = ?', artist) if artist != ''
    products
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  validates :name, :description, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params.key?('srch_term')
      product_for_search
    else
      @products = Product.all.page(params[:page]).per(5).order(:name)
    end
    @artists = Artist.all.order(:name)
    @product_types = ProductType.all.order:name
  end

  def show
    @product = Product.find(params[:id])
  end

  def filter_data
    @artist = params[:product][:artist_id]
    @product_type = params[:product][:product_type_id]
    @on_sale = params.key?('on_sale') ? 'yes' : 'no'
    @new = params.key?('new') ? 'yes' : 'no'

    unless @artist == '' || @product_type == ''
      @products = Product.joins(:artist, :product_type)
                         .where('artists.id = ?', @artist)
                         .where('product_types.id = ?', @product_type)
                         .where('products.on_sale = \'yes\' OR products.on_sale = ?', @on_sale)
                         .where('products.new = \'yes\' OR products.new = ?', @new)
                         .page(params[:page]).per(5)
    end
    if @artist == '' && @product_type == ''
      @products = Product.where('products.on_sale = \'yes\' OR products.on_sale = ?', @on_sale)
                         .where('products.new = \'yes\' OR products.new = ?', @new)
                         .page(params[:page]).per(5)

    elsif @artist == ''
      @products = Product.joins(:product_type)
                         .where('product_types.id = ?', @product_type)
                         .where('products.on_sale = \'yes\' OR products.on_sale = ?', @on_sale)
                         .where('products.new = \'yes\' OR products.new = ?', @new)
                         .page(params[:page]).per(5)
    elsif @product_type == ''
      @products = Product.joins(:artist)
                         .where('artists.id = ?', @artist)
                         .where('products.on_sale = \'yes\' OR products.on_sale = ?', @on_sale)
                         .where('products.new = \'yes\' OR products.new = ?', @new)
                         .page(params[:page]).per(5)
    end
    @artists = Artist.all.order(:name)
    @product_types = ProductType.all.order(:name)
    render :index
  end

  def product_for_search
    artist = params[:product][:artist_id].to_s
    @products = Product.search_by_category(artist, params[:srch_term])
                       .page(params[:page]).per(5).order(:name)
  end

  def add_to_cart
    @product = Product.find(params[:id])
    quantity_param = params[:quantity].to_i
    @quantity = quantity_param if quantity_param > 0
    add_session_variables(params[:id].to_i, @quantity) if @quantity
    render :show, product: @product
  end

  def add_session_variables(id, quantity)
    session[:cart] ||= []
    session[:cart] << [id, quantity] unless product_in_cart?(id, quantity)
    flash[:added] = 'Added to Cart' if @quantity
  end

  def product_in_cart?(id, quantity)
    found = false
    session[:cart].each do |item|
      if item[0] == id
        item[1] += quantity
        found = true
      end
    end
    found
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.slim
.product
  h2 = product.name
  p
    strong> Price:
    = number_to_currency product.price

    p = product.description
    - unless product.image_file_name.empty?
      = image_tag product.image.url(:small)
    - if full_details
      p = link_to 'details', product
    - else
      =form_tag product_path do |f|
        form.navbar-form role="add_to_cart" 
          .input-group.add-on
            input#add_to_cart.form-control name="quantity" placeholder="Quantity" type="number" min="0" value=@quantity /                
            .input-group-btn
              button.btn.btn-defasult type="submit" Add to Cart
              - if flash[:added]
                  = flash[:added]
        
= debug params
= debug session[:cart].inspect

app/views/products/index.html.slim
.page-header
  
  h1
    | Sweet Merch    
  div.panel.panel-default
    div.panel-body
      .container
        .col-md-3
          form.navbar-form role="search" 
            .input-group.add-on
              input#srch-term.form-control name="srch_term" placeholder="Search" type="text" /                
              .input-group-btn
                button.btn.btn-default type="submit" 
                  i.glyphicon.glyphicon-search 
            =collection_select(:product, :artist_id, @artists, :id, :name, {selected: @artist, prompt: "Select Artist"}, {class: 'form-control'})
      =form_tag products_path do |f|
        - unless params.has_key?("srch_term")
          div.panel.panel-default 
            |Filter By:
            div.row
              div.col-sm-4
                | Artist
              div.col-sm-4
                | Type of Article
              div.col-sm-4
                | New / On Sale
            div.row        
              div.col-sm-4   
                =collection_select(:product, :artist_id, @artists, :id, :name, {selected: @artist, prompt: "Select Artist"}, {class: 'form-control'})      

              div.col-sm-4   
                =collection_select(:product, :product_type_id, @product_types, :id, :name, {selected: @product_type, prompt: "Select Type"}, {class: 'form-control'})      
              
              div.col-sm-2
                .checkbox
                  label.checkbox-inline
                  input type="checkbox" name="on_sale" value="on_sale" checked=('true' if @on_sale == "yes") 
                  | On sale
              div.col-sm-2
                .checkbox
                  label.checkbox-inline
                  input type="checkbox" name="new" value="new" checked=('true' if @new == "yes")
                  | New
            div.row
              div.col-md-2
                button.btn.btn-primary type="submit"  Apply Filters   
                      
        

    =render partial: 'product', collection: @products, locals: {full_details: true}
  =paginate @products
  =page_entries_info @products
  = debug params

app/views/products/show.html.slim
#page-content-wrapper
  button.hamburger.is-closed data-toggle="offcanvas" type="button" 
    span.hamb-top
    span.hamb-middle
    span.hamb-bottom
  .container
    .row
      .col-lg-8.col-lg-offset-2
        .page-header
          h1
            | Product Details
            = render partial: 'product', object: @product, locals: {full_details: false}
    


  
  